#
spring.profiles.active=dev
#
spring.output.ansi.enabled=ALWAYS
logging.level.root=WARN
logging.level.es.upm.miw=DEBUG
# Server web ----------------------------------------------
spring.jackson.default-property-inclusion=NON_NULL
# Application http://**/actuator/info ---------------------
management.endpoints.web.exposure.include=health,info
info.app.artifact=@project.artifactId@
info.app.version=@project.version@
info.app.build=@maven.build.timestamp@
#JWT  -----------------------------------------------------
miw.jwt.expire=3600
miw.jwt.issuer=es-upm-upm
#mail
spring.mail.smtp_data=is_not_present
spring.mail.defaultEncoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_username
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false
#slack
miw.slack.uri=${SLACK_URI}
