name: CI
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Test - Unit & Integration & SonarCloud Scan & Slack WebHook
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-mode
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: Slack WebHook
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,author,commit,author,workflow, # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      - name: Sonar
        if: success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=es.upm.miw:betca-tpv-core
          -Dsonar.organization=miw-upm-github
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
